// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NetPonto.Specflow.AcceptanceTest3.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("História 001 - Enviar a amigo")]
    public partial class Historia001_EnviarAAmigoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Story-001.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-PT"), "História 001 - Enviar a amigo", "Quando preencho o formulário de enviar a amigo, é enviado um email", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Preencher formulário de enviar a amigo envia email")]
        [NUnit.Framework.CategoryAttribute("priority1")]
        [NUnit.Framework.TestCaseAttribute("paulo.iap@gmail.com", null)]
        [NUnit.Framework.TestCaseAttribute("seesharptec@gmail.com", null)]
        [NUnit.Framework.TestCaseAttribute("jorgesalitre@gmail.com", null)]
        public virtual void PreencherFormularioDeEnviarAAmigoEnviaEmail(string email, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "priority1"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Preencher formulário de enviar a amigo envia email", @__tags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("que estou no formulário \"enviar a amigo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 8
  testRunner.And(string.Format("preenchi os campos com o nome \"Sergio\" e endereço \"{0}\"", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
 testRunner.When("carrego no botão “enviar”", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 10
 testRunner.Then("um email é enviado para o meu amigo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Preencher formulário de enviar a amigo não envia email")]
        [NUnit.Framework.TestCaseAttribute("", "", "Os campos são obrigatórios!", null)]
        [NUnit.Framework.TestCaseAttribute("Eu", "", "Os campos são obrigatórios!", null)]
        [NUnit.Framework.TestCaseAttribute("", "foo@bar.com", "Os campos são obrigatórios!", null)]
        [NUnit.Framework.TestCaseAttribute("Z", "paulo.iap@gmail.com", "2 a 24 letras, sem números nem símbolos", null)]
        [NUnit.Framework.TestCaseAttribute("Sérgio81", "seesharptec@gmail.com", "2 a 24 letras, sem números nem símbolos", null)]
        [NUnit.Framework.TestCaseAttribute("_darkoolfxper666", "darkjorgesalitre@gmail.com", "2 a 24 letras, sem números nem símbolos", null)]
        [NUnit.Framework.TestCaseAttribute("José Povinho", "foo", "o endereço de email não é válido", null)]
        [NUnit.Framework.TestCaseAttribute("John Doe", "seesharptec_at_gmail.com", "o endereço de email não é válido", null)]
        public virtual void PreencherFormularioDeEnviarAAmigoNaoEnviaEmail(string nome, string email, string erro, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Preencher formulário de enviar a amigo não envia email", exampleTags);
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("que estou no formulário \"enviar a amigo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 20
  testRunner.And(string.Format("preenchi os campos com o nome \"{0}\" e endereço \"{1}\"", nome, email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 21
 testRunner.When("carrego no botão “enviar”", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 22
 testRunner.Then(string.Format("é mostrada uma mensagem de erro com o texto \"{0}\"", erro), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 23
  testRunner.And("nenhum email é enviado para o meu amigo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
